### ISSUE TITLE
Compilation with APRON fails

### ISSUE THREAD

**Issue by alexjung** [eth-srl/ELINA#12]
Hi,
I've encountered an issue while trying to compile ELISA with APRON.
Following the instructions on your website and using the option `IS_APRON = -DHAS_APRON` in Makefile.config compilation terminates in two errors:
```
zonotope_internal.h: In function ‘zonotope_aff_bound’:
zonotope_internal.h:535:7: error: implicit declaration of function ‘elina_coeff_set_interval_double’ [-Werror=implicit-function-declaration]
       elina_coeff_set_interval_double(&linexpr0->p.linterm[k].coeff, p->inf,p->sup);
```
and
```
zonotope_internal.h: In function ‘elina_linexpr0_from_zonotope’:
zonotope_internal.h:929:3: error: implicit declaration of function ‘elina_coeff_set_scalar_double’ [-Werror=implicit-function-declaration]
   elina_coeff_set_scalar_double(&res->p.linterm[k].coeff, p->inf);
```

The problem is obviously that the two functions `elina_coeff_set_interval_double()` and `elina_coeff_set_scalar_double()` are declared in `elina_coeff.h` which is only included in `zonotope.h` if `HAS_APRON` is **not** defined.
Compiling with the option `IS_APRON = #-DHAS_APRON` results in a successful compilation.

Thanks in advance for looking into this!

Best regards
Alex

**Comment by GgnDpSngh** [comment]
Thanks, for pointing this out. It has been fixed now.
