### ISSUE TITLE
Test result of Abstract1.expand in mlexample.byte

### ISSUE THREAD

**Issue by skcho** [eth-srl/ELINA#15]
Hello. When running `ocaml_interface/mlexample.byte` (and `mlexample.opt`), the test result of `Abstract1.expand` looks strange.
```
abs=[|3x+4y-6=0; 2w+z-1>=0; -2w-z+4>=0; u>=0; -u+5>=0|]
p2=expand(abs,y,[y1,y2]))=[|3x+4v-6=0; y-v=0; u-v=0; 2w+z-1>=0; -2w-z+4>=0;
                            a>=0; -a+5>=0|]
```
There is no expanded variables such as `y1` and `y2`, in the constraints. The below is the test result after changing it to use Apron's Polka instead of Elina_poly with the same OCaml code.
```
abs=[|3x+4y-6=0; -2w-z+4>=0; -u+5>=0; u>=0; 2w+z-1>=0|]
p2=expand(abs,y,[y1,y2]))=[|3x+4y2-6=0; 3x+4y1-6=0; 3x+4y-6=0; -2w-z+4>=0;
                            -u+5>=0; u>=0; 2w+z-1>=0|]
```
Am I the only one who has the issue?

**Comment by GgnDpSngh** [comment]
Hi,

There was a bug in the test example. It was creating y as real valued variable which ELINA does not currently support. This has been fixed now and the output of expand contains y1,y2.

Cheers,
Gagan

**Comment by skcho** [comment]
Thank you for the quick fix!
