### ISSUE TITLE
Complete OPAM packaging

### ISSUE THREAD

**Issue by skcho** [eth-srl/ELINA#18]
(I copied comments from #16 here, because it seems to be more visible.)

Hi Gagan,

Thank you very much for the review and merge. :heart:

In order to complete the OPAM packaging, we need to do some more things.

1. Making a tarball (e.g. `elina-1.0.tar.gz`) for the package manager to get the same files by its version name.
    * Since your repository is on GitHub, I think it is enough to add a git tag with the version name, then we can use the tarball link from GitHub, e.g., https://github.com/skcho/ELINA/archive/1.0.tar.gz .
    * Otherwise, you can use your own server (http://elina.ethz.ch/) to distribute the tarball.

2. Adding ELINA's info to the main opam repository: If the tarball link is prepared, we can make a PR to [the main opam repository](https://github.com/ocaml/opam-repository/), which makes opam users can easily install ELINA with one command, `opam install elina`.

Though (1) is impossible for me as I can't change tags on your repository, I can do (2) if you are happy with that. :wink:

Sincerely,
Sungkeun

**Comment by GgnDpSngh** [comment]
Hi Sungkeun,

Thanks for the suggestion. I have added the elina-1.0.tar.gz tarball at [http://elina.ethz.ch/](http://elina.ethz.ch/) as per your suggestion. Do you think it is sufficient to complete the OPAM packaging?

Cheers,
Gagan

**Comment by skcho** [comment]
> Do you think it is sufficient to complete the OPAM packaging?

I believe so. Let's see what happens in the CI of opam repository. I will make a PR shortly. 😄

**Comment by skcho** [comment]
I sent a PR: ocaml/opam-repository/pull/11815

**Comment by skcho** [comment]
Hi Gagan,

The PR has been merged. So, now OCaml users can use ELINA with `opam install elina`. :tada: Thank you so much for your development and support!

Sincerely,
Sungkeun

**Comment by GgnDpSngh** [comment]
Hi Sungkeun,

Thanks a lot for helping to make ELINA easier to install. Let me know if there are any further issues with ELINA.

Cheers,
Gagan
