### ISSUE TITLE
Apron support?

### ISSUE THREAD

**Issue by xapantu** [eth-srl/ELINA#4]
I noticed that Apron support was gone since cc697b524f4e81d46df21d9a1e3a8010f8ec4505, however it was useful to be interfaced with projects already supporting Apron. Moreover it more or less provide OCaml support for free.

Do you plan to reconsider?

**Comment by GgnDpSngh** [comment]
We will provide an APRON interface soon (hopefully by the end of this week) so that the existing analyzers using APRON do not need to change a lot for interfacing with ELINA.
