### ISSUE TITLE
segmentation fault: ./elina_test_poly 5 5

### ISSUE THREAD

**Issue by monniaux** [eth-srl/ELINA#6]
Hi

I tried ./elina_test_poly 5 5 and got
Testing Meet
..ELINA Input Polyhedra
array of constraints of size 4
 0: x0 + 3 >= 0
 1: x2 + 3 >= 0
 2: x3 + 2x4 + 9 >= 0
 3: 2x3 + x4 + 7 >= 0
array of constraints of size 4
 0: x1 + 6 >= 0
 1: x2 >= 0
 2: x4 + 3 >= 0
 3: 2x3 + x4 >= 0
ELINA Output Polyhedron
array of constraints of size 5
 0: x4 + 3 >= 0
 1: 2x3 + x4 >= 0
 2: x2 >= 0
 3: x0 + 3 >= 0
 4: x1 + 6 >= 0
Testing Join
..ELINA Input Polyhedra
array of constraints of size 2
 0: 2x0 + x1 + 2 >= 0
 1: x3 + x4 + 3 >= 0
array of constraints of size 4
 0: 2x0 + x1 + 4 >= 0
 1: x2 + 4 >= 0
 2: x3 >= 0
 3: x3 + x4 + 3 >= 0
ELINA Output Polyhedron
array of constraints of size 2
 0: x3 + x4 + 3 >= 0
 1: 2x0 + x1 + 4 >= 0
Testing Assign
.ELINA Input Polyhedron
array of constraints of size 3
 0: x0 + x1 = 0
 1: x3 + 2x4 + 9 >= 0
 2: 2x3 + x4 + 6 >= 0
Assignment statement
x4 = 2x0 + 5
ELINA Output Polyhedron
array of constraints of size 2
 0: 2x0 - x4 + 5 = 0
 1: -2x1 - x4 + 5 = 0

Testing Fold
.ELINA Input Polyhedron
array of constraints of size 3
 0: x0 + 2x1 + 2 >= 0
 1: x2 >= 0
 2: x4 + 4 >= 0
Dimensions: 2 3 

Then segmentation fault.

**Comment by GgnDpSngh** [comment]
Thanks for your feedback. It is fixed now.
